version: '3.9'
services:
  service-db:
    image: postgres
    container_name: S21DataBase
    env_file:
      - "./config_db.env"
    volumes:
      - ./dist/database:/var/lib/postgresql/data/pgdata/
    restart: unless-stopped

  service-flyway:
    image: flyway/flyway
    container_name: S21FlyWay
    command: -configFiles=/flyway/conf/flyway.config -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    volumes:
      - ./helper/flyway_config:/flyway/conf/
      - ./helper/flyway_migration:/flyway/sql
    depends_on:
      service-db:
        condition: service_started

  service-backend:
    image: backend_info
    container_name: S21BackEnd
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      service-flyway:
        condition: service_completed_successfully
    env_file:
      - "./config_backend.env"
    volumes:
      - ./dist/logs:/app/logs
#    ports:
#      - "8080:8080"

  service-nginx:
    image: nginx
    container_name: S21Nginx
    restart: always
    depends_on:
      service-backend:
        condition: service_started
    ports:
      - "80:80"
    volumes:
      - ./helper/nginx:/etc/nginx/conf.d

  service-pgadmin:
    image: dpage/pgadmin4:7
    container_name: S21PGadmin
    env_file:
      - "./config_pgadmin.env"
    ports:
      - "5050:80"
    volumes:
      - ./dist/pgadmin:/var/lib/pgadmin
#      - ./pgadmin_config/servers.json:/pgadmin4/servers.json
#      - ./pgadmin_config/pgpass:/pgpass
    restart: always
